name: hikemate
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  google_sign_in: ^6.2.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  gpx: ^2.2.0
  path_provider: ^2.1.2
  fluttertoast: ^8.2.4
  fl_chart: ^0.66.0
  http: ^1.2.0
  intl: ^0.19.0
  geocoding: ^2.2.0
  cupertino_icons: ^1.0.8
  video_player: ^2.10.1
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/splash_screen.gif
    - assets/gpx/
